### ISSUE TITLE
No such property exception

### ISSUE THREAD

**Issue by bearrito** [Mindera/gradle-slack-plugin#10]
Running version 1.0.4

I am seeing the following error

Exception

```
* Where:
Build file '/home/barrett/Git/gradle_tests/build.gradle' line: 92

* What went wrong:
A problem occurred evaluating root project 'gradle_tests'.
> No such property: enabled for class: com.mindera.gradle.slack.SlackPluginExtension_Decorated
```

Snippet from build

```
apply plugin: 'com.mindera.gradle.slack'
slack {
    url 'https://hooks.slack.com/services/REDACTED'
    dependsOnTasks 'releaseTask'
    title 'release-hook'
    enabled = false
}

```

**Comment by prudencioj** [comment]
Can you check if with the latest release it still happens? Version 1.0.7
And you should have enabled set to true in order to get it working.
I am also not sure the url for the hook is correct, please check the steps to get the url from the readme.

**Comment by jglanfield** [comment]
Works after updating to 1.0.7
